
"use client";

import { useState, useEffect } from 'react';

export type Language = 'en' | 'sw';

const translations = {
  en: {
    dashboard: "Dashboard",
    fleet: "Fleet",
    finance: "Finance",
    inventory: "Inventory Control",
    map: "Live Map",
    trips: "Trips & Dispatch",
    users: "User Management",
    notifications: "Notifications",
    logout: "Logout",
    active_mission: "Active Mission",
    mileage: "Mileage",
    earnings: "Earnings",
    complete_delivery: "Complete Delivery",
    start_nav: "Start Navigator",
    proof: "Proof",
    expense: "Expense",
    issue: "Report Issue",
    capture: "Capture Photo",
    take_photo: "Take Photo",
    switch_lang: "Kiswahili",
    revenue: "Total Revenue",
    expenses: "Expenses",
    net_profit: "Net Profit",
    recent_income: "Recent Income",
    recent_expenses: "Recent Expenses",
    add_vehicle: "Add Vehicle",
    warehouse: "Warehouse Inventory",
    dispatch: "Dispatch New Trip",
    camera_access: "Camera Access Required",
    camera_desc: "Please allow camera access to capture evidence.",
    report_breakdown: "Report Breakdown",
    report_maintenance: "Maintenance Need",
    issue_description: "What is wrong with the vehicle?",
    submit_report: "Send Emergency Report",
    severity: "Severity Level",
    agent_contact: "Agent Contact",
    support: "Support",
    command_dashboard: "Command Dashboard",
    strategic_overview: "Strategic overview for CEO and Operations.",
    active_fleet: "Active Fleet Overview",
    live_updates: "Live Updates",
    maintenance_hub: "Maintenance Hub",
    real_time_health: "Real-time fleet health and service control.",
    tasks_pending: "Tasks Pending",
    in_progress: "In Progress",
    quick_action: "Quick Action",
    check_history: "Check Truck History",
    active_queue: "Active Queue",
    recent_activity: "Recent Maintenance Activity",
    financial_dashboard: "Financial Dashboard",
    audit_revenue: "Audit company revenue and authorize expenditures.",
    unpaid_invoices: "Unpaid Invoices",
    cash_reserves: "Cash Reserves",
    approval_queue: "Expense Approval Queue",
    ai_insights: "AI Fleet Insights",
    analyze_fleet: "Analyze Fleet",
    harness_intelligence: "Harness Fleet Intelligence",
    parts_requests: "Parts Requests",
    fleet_status: "Fleet Status",
    fleet_map: "Fleet Map",
    service_requests: "Service Requests",
    truck_history: "Truck History",
    fuel_approvals: "Fuel Approvals",
    allowances: "Allowances",
    monthly_report: "Monthly Report",
    recent_issues: "Recent Issues",
    critical_alert: "Critical Alert: Breakdown Reported",
    immediate_action: "Immediate Action Required",
    revenue_vs_expenses: "Revenue vs Expenses",
    fuel_consumption: "Fuel Consumption (L)",
    total_trucks: "Total Trucks",
    active_trips: "Active Trips",
    online_drivers: "Drivers Online",
    low_stock: "Low Stock",
    home: "Home",
    profile: "Profile",
    overview: "Overview",
    income: "Income",
    fuel: "Fuel",
    request_parts: "Request Spare Parts",
    part_name: "Part Name / Service",
    quantity: "Quantity",
    urgency: "Urgency",
    reason: "Reason for Request",
    submit_request: "Submit Resource Request",
    my_requests: "My Parts Requests",
  },
  sw: {
    dashboard: "Dashibodi",
    fleet: "Karakana",
    finance: "Fedha",
    inventory: "Usimamizi wa Hesabu",
    map: "Ramani ya Moja kwa Moja",
    trips: "Safari na Usimamizi",
    users: "Watumiaji",
    notifications: "Arifa",
    logout: "Ondoka",
    active_mission: "Kazi Inayoendelea",
    mileage: "Umbali",
    earnings: "Mapato",
    complete_delivery: "Kamilisha Uwasilishaji",
    start_nav: "Anza Ramani",
    proof: "Ushahidi",
    expense: "Gharama",
    issue: "Ripoti Tatizo",
    capture: "Piga Picha",
    take_photo: "Piga Picha",
    switch_lang: "English",
    revenue: "Jumla ya Mapato",
    expenses: "Gharama",
    net_profit: "Faida Safi",
    recent_income: "Mapato ya Hivi Karibuni",
    recent_expenses: "Gharama za Hivi Karibuni",
    add_vehicle: "Ongeza Gari",
    warehouse: "Hesabu ya Ghala",
    dispatch: "Anza Safari Mpya",
    camera_access: "Ufikiaji wa Kamera Unahitajika",
    camera_desc: "Tafadhali ruhusu ufikiaji wa kamera ili kupiga picha ya ushahidi.",
    report_breakdown: "Ripoti Gari Kuharibika",
    report_maintenance: "Mahitaji ya Matengenezo",
    issue_description: "Gari lina tatizo gani?",
    submit_report: "Tuma Ripoti ya Dharura",
    severity: "Kiwango cha Tatizo",
    agent_contact: "Nambari ya Wakala",
    support: "Msaada",
    command_dashboard: "Dashibodi ya Amri",
    strategic_overview: "Muhtasari wa kimkakati kwa CEO na Operesheni.",
    active_fleet: "Muhtasari wa Magari Yanayotumika",
    live_updates: "Habari za Moja kwa Moja",
    maintenance_hub: "Kituo cha Matengenezo",
    real_time_health: "Udhibiti wa afya ya magari na huduma kwa wakati halisi.",
    tasks_pending: "Kazi Zinazosubiri",
    in_progress: "Inaendelea",
    quick_action: "Hatua ya Haraka",
    check_history: "Angalia Historia ya Gari",
    active_queue: "Foleni Inayoendelea",
    recent_activity: "Shughuli za Hivi Karibuni za Matengenezo",
    financial_dashboard: "Dashibodi ya Fedha",
    audit_revenue: "Kagua mapato ya kampuni na idhinisha matumizi.",
    unpaid_invoices: "Ankara Zisizolipwa",
    cash_reserves: "Akiba ya Fedha",
    approval_queue: "Foleni ya Idhini ya Gharama",
    ai_insights: "Ufahamu wa AI wa Magari",
    analyze_fleet: "Chambua Magari",
    harness_intelligence: "Tumia Akili ya Magari",
    parts_requests: "Maombi ya Vipuri",
    fleet_status: "Hali ya Magari",
    fleet_map: "Ramani ya Magari",
    service_requests: "Maombi ya Huduma",
    truck_history: "Historia ya Gari",
    fuel_approvals: "Idhini ya Mafuta",
    allowances: "Marupurupu",
    monthly_report: "Ripoti ya Mwezi",
    recent_issues: "Matatizo ya Hivi Karibuni",
    critical_alert: "Arifa Muhimu: Gari Limeharibika",
    immediate_action: "Hatua ya Haraka Inahitajika",
    revenue_vs_expenses: "Mapato dhidi ya Gharama",
    fuel_consumption: "Matumizi ya Mafuta (L)",
    total_trucks: "Jumla ya Malori",
    active_trips: "Safari Zinazoendelea",
    online_drivers: "Madereva Wapo Mtandaoni",
    low_stock: "Bidhaa Chache",
    home: "Nyumbani",
    profile: "Wasifu",
    overview: "Muhtasari",
    income: "Mapato",
    fuel: "Mafuta",
    request_parts: "Omba Vipuri / Huduma",
    part_name: "Jina la Kipuri / Huduma",
    quantity: "Idadi",
    urgency: "Uharaka",
    reason: "Sababu ya Ombi",
    submit_request: "Tuma Ombi la Rasilimali",
    my_requests: "Maombi Yangu ya Vipuri",
  }
};

export function useLanguage() {
  const [lang, setLang] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('fleet_lang') as Language;
    if (saved) setLang(saved);
  }, []);

  const toggleLanguage = () => {
    const next = lang === 'en' ? 'sw' : 'en';
    setLang(next);
    localStorage.setItem('fleet_lang', next);
  };

  const t = translations[lang];

  return { lang, toggleLanguage, t };
}
