
"use client";

import { useState, useEffect } from 'react';

export type Language = 'en' | 'sw';

const translations = {
  en: {
    dashboard: "Dashboard",
    fleet: "Fleet",
    finance: "Finance",
    inventory: "Inventory Control",
    map: "Live Map",
    trips: "Trips & Dispatch",
    users: "User Management",
    notifications: "Notifications",
    logout: "Logout",
    active_mission: "Active Mission",
    mileage: "Mileage",
    earnings: "Earnings",
    complete_delivery: "Complete Delivery",
    start_nav: "Start Navigator",
    proof: "Proof",
    expense: "Expense",
    issue: "Report Issue",
    capture: "Capture Photo",
    take_photo: "Take Photo",
    switch_lang: "Kiswahili",
    revenue: "Total Revenue",
    expenses: "Expenses",
    net_profit: "Net Profit",
    recent_income: "Recent Income",
    recent_expenses: "Recent Expenses",
    add_vehicle: "Add Vehicle",
    warehouse: "Warehouse Inventory",
    dispatch: "Dispatch New Trip",
    camera_access: "Camera Access Required",
    camera_desc: "Please allow camera access to capture evidence.",
    report_breakdown: "Report Breakdown",
    report_maintenance: "Maintenance Need",
    issue_description: "What is wrong with the vehicle?",
    submit_report: "Send Emergency Report",
    severity: "Severity Level",
    agent_contact: "Agent Contact",
    support: "Support",
    command_dashboard: "Command Dashboard",
    strategic_overview: "Strategic overview for CEO and Operations.",
    active_fleet: "Active Fleet Overview",
    live_updates: "Live Updates",
    maintenance_hub: "Maintenance Hub",
    real_time_health: "Real-time fleet health and service control.",
    tasks_pending: "Tasks Pending",
    in_progress: "In Progress",
    quick_action: "Quick Action",
    check_history: "Check Truck History",
    active_queue: "Active Queue",
    recent_activity: "Recent Maintenance Activity",
    financial_dashboard: "Financial Dashboard",
    audit_revenue: "Audit company revenue and authorize expenditures.",
    unpaid_invoices: "Unpaid Invoices",
    cash_reserves: "Cash Reserves",
    approval_queue: "Expense Approval Queue",
    ai_insights: "AI Fleet Insights",
    analyze_fleet: "Analyze Fleet",
    harness_intelligence: "Harness Fleet Intelligence",
    parts_requests: "Parts Requests",
    fleet_status: "Fleet Status",
    fleet_map: "Fleet Map",
    service_requests: "Service Requests",
    truck_history: "Truck History",
    fuel_approvals: "Fuel Approvals",
    allowances: "Allowances",
    monthly_report: "Monthly Report",
    recent_issues: "Recent Issues",
    critical_alert: "Critical Alert: Breakdown Reported",
    immediate_action: "Immediate Action Required",
    revenue_vs_expenses: "Revenue vs Expenses",
    fuel_consumption: "Fuel Consumption (L)",
    total_trucks: "Total Trucks",
    active_trips: "Active Trips",
    online_drivers: "Drivers Online",
    low_stock: "Low Stock",
    home: "Home",
    profile: "Profile",
    overview: "Overview",
    income: "Income",
    fuel: "Fuel",
    request_parts: "Request Spare Parts",
    part_name: "Part Name / Service",
    quantity: "Quantity",
    urgency: "Urgency",
    reason: "Reason for Request",
    submit_request: "Submit Resource Request",
    my_requests: "My Parts Requests",
    assigned_work: "Assigned work",
    your_allowances: "Your allowances",
    allowance_total: "Total credited",
    no_assigned_trips: "No trips assigned yet.",
    no_allowance_records: "No allowance records linked to your account yet.",
    trip_status: "Status",
    assignments_hint: "Operations add new trips here when you are dispatched.",
  },
  sw: {
    dashboard: "Dashibodi",
    fleet: "Karakana",
    finance: "Fedha",
    inventory: "Usimamizi wa Hesabu",
    map: "Ramani ya Moja kwa Moja",
    trips: "Safari na Usimamizi",
    users: "Watumiaji",
    notifications: "Arifa",
    logout: "Ondoka",
    active_mission: "Kazi Inayoendelea",
    mileage: "Umbali",
    earnings: "Mapato",
    complete_delivery: "Kamilisha Uwasilishaji",
    start_nav: "Anza Ramani",
    proof: "Ushahidi",
    expense: "Gharama",
    issue: "Ripoti Tatizo",
    capture: "Piga Picha",
    take_photo: "Piga Picha",
    switch_lang: "English",
    revenue: "Jumla ya Mapato",
    expenses: "Gharama",
    net_profit: "Faida Safi",
    recent_income: "Mapato ya Hivi Karibuni",
    recent_expenses: "Gharama za Hivi Karibuni",
    add_vehicle: "Ongeza Gari",
    warehouse: "Hesabu ya Ghala",
    dispatch: "Anza Safari Mpya",
    camera_access: "Ufikiaji wa Kamera Unahitajika",
    camera_desc: "Tafadhali ruhusu ufikiaji wa kamera ili kupiga picha ya ushahidi.",
    report_breakdown: "Ripoti Gari Kuharibika",
    report_maintenance: "Mahitaji ya Matengenezo",
    issue_description: "Gari lina tatizo gani?",
    submit_report: "Tuma Ripoti ya Dharura",
    severity: "Kiwango cha Tatizo",
    agent_contact: "Nambari ya Wakala",
    support: "Msaada",
    command_dashboard: "Dashibodi ya Amri",
    strategic_overview: "Muhtasari wa kimkakati kwa CEO na Operesheni.",
    active_fleet: "Muhtasari wa Magari Yanayotumika",
    live_updates: "Habari za Moja kwa Moja",
    maintenance_hub: "Kituo cha Matengenezo",
    real_time_health: "Udhibiti wa afya ya magari na huduma kwa wakati halisi.",
    tasks_pending: "Kazi Zinazosubiri",
    in_progress: "Inaendelea",
    quick_action: "Hatua ya Haraka",
    check_history: "Angalia Historia ya Gari",
    active_queue: "Foleni Inayoendelea",
    recent_activity: "Shughuli za Hivi Karibuni za Matengenezo",
    financial_dashboard: "Dashibodi ya Fedha",
    audit_revenue: "Kagua mapato ya kampuni na idhinisha matumizi.",
    unpaid_invoices: "Ankara Zisizolipwa",
    cash_reserves: "Akiba ya Fedha",
    approval_queue: "Foleni ya Idhini ya Gharama",
    ai_insights: "Ufahamu wa AI wa Magari",
    analyze_fleet: "Chambua Magari",
    harness_intelligence: "Tumia Akili ya Magari",
    parts_requests: "Maombi ya Vipuri",
    fleet_status: "Hali ya Magari",
    fleet_map: "Ramani ya Magari",
    service_requests: "Maombi ya Huduma",
    truck_history: "Historia ya Gari",
    fuel_approvals: "Idhini ya Mafuta",
    allowances: "Marupurupu",
    monthly_report: "Ripoti ya Mwezi",
    recent_issues: "Matatizo ya Hivi Karibuni",
    critical_alert: "Arifa Muhimu: Gari Limeharibika",
    immediate_action: "Hatua ya Haraka Inahitajika",
    revenue_vs_expenses: "Mapato dhidi ya Gharama",
    fuel_consumption: "Matumizi ya Mafuta (L)",
    total_trucks: "Jumla ya Malori",
    active_trips: "Safari Zinazoendelea",
    online_drivers: "Madereva Wapo Mtandaoni",
    low_stock: "Bidhaa Chache",
    home: "Nyumbani",
    profile: "Wasifu",
    overview: "Muhtasari",
    income: "Mapato",
    fuel: "Mafuta",
    request_parts: "Omba Vipuri / Huduma",
    part_name: "Jina la Kipuri / Huduma",
    quantity: "Idadi",
    urgency: "Uharaka",
    reason: "Sababu ya Ombi",
    submit_request: "Tuma Ombi la Rasilimali",
    my_requests: "Maombi Yangu ya Vipuri",
    assigned_work: "Kazi uliyopewa",
    your_allowances: "Marupurupu yako",
    allowance_total: "Jumla iliyorekodiwa",
    no_assigned_trips: "Bado hakuna safari zilizopewa.",
    no_allowance_records: "Bado hakuna marupurupu yaliyounganishwa na akaunti yako.",
    trip_status: "Hali",
    assignments_hint: "Operesheni huongeza safari hapa unapopewa kazi.",
  }
};

// Sidebar navigation labels come straight from route-config.ts as plain
// English strings (not short dictionary keys like the rest of this file),
// since route-config drives ~150 routes across the whole app. Rather than
// add a Swahili field to every RouteConfig entry, this is a lookup from
// the exact English label to its Swahili translation, applied at render
// time in Sidebar wherever `item.label` is shown. Unmapped labels (a new
// route added later without an entry here) just render in English.
const navLabelsSw: Record<string, string> = {
  "AI Operations": "Uendeshaji wa AI",
  "Aging Report": "Ripoti ya Umri wa Madeni",
  "All Employees": "Wafanyakazi Wote",
  "Approvals Inbox": "Sanduku la Idhini",
  "Audit Trail": "Kumbukumbu za Ukaguzi",
  "Balance Sheet": "Mizania",
  "Bank Accounts": "Akaunti za Benki",
  "Bank Reconciliation": "Upatanisho wa Benki",
  "Bank Statement Detail": "Maelezo ya Taarifa ya Benki",
  "Bank Statements": "Taarifa za Benki",
  "Bank Transactions": "Miamala ya Benki",
  "Bookings": "Uhifadhi",
  "Budgets": "Bajeti",
  "Bulk Expenses": "Gharama kwa Wingi",
  "Bulk Insurance Import": "Uingizaji wa Bima kwa Wingi",
  "COA Reconciliation": "Upatanisho wa Mchoro wa Hesabu",
  "Cash Flow": "Mtiririko wa Fedha",
  "Cash Requests": "Maombi ya Fedha Taslimu",
  "Chart of Accounts": "Mchoro wa Hesabu",
  "Client Email": "Barua Pepe ya Mteja",
  "Company AI": "AI ya Kampuni",
  "Credit Notes": "Noti za Mkopo",
  "Customer Details": "Maelezo ya Mteja",
  "Customer Invoices": "Ankara za Wateja",
  "Customer Tracking": "Ufuatiliaji wa Wateja",
  "Customers": "Wateja",
  "Dashboard": "Dashibodi",
  "Day-End Closings": "Ufungaji wa Siku",
  "Disciplinary Cases": "Kesi za Kinidhamu",
  "Dispatch Board": "Ubao wa Usafirishaji",
  "Driver Compliance": "Uzingatiaji wa Dereva",
  "Driver Management": "Usimamizi wa Madereva",
  "Driver Performance": "Utendaji wa Dereva",
  "Driver Profile": "Wasifu wa Dereva",
  "Employee Loans": "Mikopo ya Wafanyakazi",
  "Executive Command Center": "Kituo cha Amri cha Uongozi",
  "Expense Analysis": "Uchambuzi wa Gharama",
  "Expense Approval": "Idhini ya Gharama",
  "Expense Tracking": "Ufuatiliaji wa Gharama",
  "Expense Transactions": "Miamala ya Gharama",
  "FX Rates": "Viwango vya Ubadilishaji Fedha",
  "Finance Overview": "Muhtasari wa Fedha",
  "Financial Reports": "Ripoti za Fedha",
  "Fuel Approvals": "Idhini za Mafuta",
  "Fuel Consumption": "Matumizi ya Mafuta",
  "Fuel Costs": "Gharama za Mafuta",
  "Fuel Fraud Alerts": "Tahadhari za Udanganyifu wa Mafuta",
  "Fuel Log": "Kumbukumbu ya Mafuta",
  "Fuel Management": "Usimamizi wa Mafuta",
  "Fuel Per Trip": "Mafuta kwa Safari",
  "General Ledger": "Daftari Kuu",
  "Insurance": "Bima",
  "Insurance Details": "Maelezo ya Bima",
  "Internal Chat": "Mazungumzo ya Ndani",
  "Journal Entries": "Kumbukumbu za Hesabu",
  "Leave": "Likizo",
  "Live Fleet Map": "Ramani ya Magari ya Moja kwa Moja",
  "LogiPRO (Legacy)": "LogiPRO (Mfumo wa Zamani)",
  "Maintenance Costs": "Gharama za Matengenezo",
  "Maintenance Records": "Kumbukumbu za Matengenezo",
  "Meetings": "Mikutano",
  "My Expenses": "Gharama Zangu",
  "My HR Records": "Kumbukumbu Zangu za Utumishi",
  "My Profile": "Wasifu Wangu",
  "My Trips": "Safari Zangu",
  "New Bank Statement": "Taarifa Mpya ya Benki",
  "New Insurance": "Bima Mpya",
  "Notifications": "Arifa",
  "Overtime": "Muda wa Ziada",
  "Parts Requests": "Maombi ya Vipuri",
  "Payments": "Malipo",
  "Payroll": "Malipo ya Mishahara",
  "Performance Reviews": "Tathmini za Utendaji",
  "Petty Cash": "Fedha Ndogo za Matumizi",
  "Profit & Loss": "Faida na Hasara",
  "Proof of Delivery": "Uthibitisho wa Uwasilishaji",
  "Purchase Orders": "Oda za Ununuzi",
  "Receipts & Storage": "Risiti na Uhifadhi",
  "Report Issue": "Ripoti Tatizo",
  "Revenue Analysis": "Uchambuzi wa Mapato",
  "Revenue Tracking": "Ufuatiliaji wa Mapato",
  "Route Optimizer": "Kiboreshaji cha Njia",
  "Route Profitability": "Faida ya Njia",
  "Sales Pipelines": "Mfumo wa Mauzo",
  "Separation & Exit": "Kuachana na Kazi",
  "Service Requests": "Maombi ya Huduma",
  "Shipments & Trips": "Mizigo na Safari",
  "Statutory Reports": "Ripoti za Kisheria",
  "Stock Items": "Bidhaa za Hisa",
  "Suppliers": "Wasambazaji",
  "System Settings": "Mipangilio ya Mfumo",
  "Tax Reports (VAT/WHT)": "Ripoti za Kodi (VAT/WHT)",
  "Trial Balance": "Mizani ya Majaribio",
  "Trip History": "Historia ya Safari",
  "Vehicle Compliance": "Uzingatiaji wa Gari",
  "Vehicle Loans": "Mikopo ya Magari",
  "Vehicle Profitability": "Faida ya Gari",
  "Vehicle Revenue": "Mapato ya Gari",
  "Vehicles": "Magari",
  "Vendor Bills": "Ankara za Wauzaji",
};

export function translateNavLabel(label: string, lang: Language): string {
  if (lang !== "sw") return label;
  return navLabelsSw[label] ?? label;
}

export function useLanguage() {
  const [lang, setLang] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('fleet_lang') as Language;
    if (saved) setLang(saved);
  }, []);

  const toggleLanguage = () => {
    const next = lang === 'en' ? 'sw' : 'en';
    setLang(next);
    localStorage.setItem('fleet_lang', next);
  };

  const t = translations[lang];

  return { lang, toggleLanguage, t };
}
